---

- hosts: all

  sudo: yes

  vars:
      host: "{{ inventory_hostname }}"

  tasks:
    - name: make sure required packages are installed
      apt: pkg=python3 state=present

    - include: tasks/foo.yml

    # Passing variables to includes.
    - include: wordpress.yml wp_user=timmy
    - include: wordpress.yml wp_user=alice
    - include: wordpress.yml wp_user=bob

    # Structured variables.
    - include: wordpress.yml
    vars:
        wp_user: timmy
        ssh_keys:
          - keys/one.txt
          - keys/two.txt